//COMANDO PARA CALCULAR A IDADE

DECLARE @IDADE INT, @DATANASC DATETIME, @HOJE DATETIME, @TEXTO VARCHAR(20)

SET @DATANASC = '19800422'
SET @HOJE = GETDATE()

SET @IDADE = YEAR(@HOJE) - YEAR(@DATANASC)

IF @IDADE = 0
BEGIN /* SE IDADE FOR 0 SIGNIFICA QUE A PESSOA TEM MES OU MESES DE IDADE */
	SET @IDADE = MONTH(@HOJE) - MONTH(@DATANASC)

	IF @IDADE > 1 
	BEGIN
		SET @TEXTO = 'meses' 
	END
	ELSE
	BEGIN
		SET @TEXTO = 'mês' 
	END
END
ELSE
IF @IDADE > 0
BEGIN
	IF MONTH(@HOJE) < MONTH(@DATANASC)
	BEGIN
		SET @IDADE = @IDADE - 1
	END
	ELSE
	IF DAY(@HOJE) < DAY(@DATANASC) AND MONTH(@HOJE) = MONTH(@DATANASC)
	BEGIN
		SET @IDADE = @IDADE - 1
	END

	IF @IDADE > 1
	BEGIN
		SET @TEXTO = 'anos'
	END
	ELSE
	BEGIN
		SET @TEXTO = 'ano'
	END
END

SELECT 
       @IDADE AS Idade,
       @TEXTO AS Idade_descricao
