//COMANDO SPLIT_STRING

ALTER DATABASE dbo.base SET COMPATIBILITY_LEVEL = 150

SELECT  
	   VALUE AS VALOR,
	   SUBSTRING(VALUE,1,CHARINDEX('-',VALUE) - 1)			AS DISCIPLINA,
	   SUBSTRING(VALUE,CHARINDEX('-',VALUE) + 1,LEN(VALUE))	AS PONTOS
  FROM STRING_SPLIT((SELECT 'NOME-1;NOME-2;NOME-3;NOME-4;NOME-5;NOME-6;'),';')
WHERE VALUE <> ''
